version: '3'

services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "trust"

  web:
    build:
      context: .
      dockerfile: ./platform/Dockerfile
    command: dagster-webserver --port 8080 --host 0.0.0.0 --workspace ./platform/workspace.yaml
    environment:
      POSTGRES_URL: postgresql://postgres@db/postgres
      REDIS_URL: redis://redis/
      DAGSTER_HOME: /app/platform
      CODE_SERVERS__DEET__HOST: code-server-deet
      CODE_SERVERS__DATA_SCIENCE__HOST: code-server-datasets-and-analysis
      CODE_SERVERS__DATASETS_AND_ANALYSIS__HOST: code-server-deet
      CODE_SERVERS__GSCIP__HOST: code-server-gscip
      CODE_SERVERS__LITE__HOST: code-server-lite
    volumes:
      - ${PWD}/teams:/app/teams
    ports:
      - "8080:8080"
    links:
      - "db"
      - "redis"
      - "code-server-deet"
      - "code-server-gscip"
      - "code-server-data-science"
      - "code-server-lite"
      - "code-server-datasets-and-analysis"

  daemon:
    build:
      context: .
      dockerfile: ./platform/Dockerfile
    command: dagster-daemon run --workspace ./platform/workspace.yaml
    environment:
      POSTGRES_URL: postgresql://postgres@db/postgres
      REDIS_URL: redis://redis/
      DAGSTER_HOME: /app/platform
      CODE_SERVERS__DEET__HOST: code-server-deet
      CODE_SERVERS__DATA_SCIENCE__HOST: code-server-datasets-and-analysis
      CODE_SERVERS__DATASETS_AND_ANALYSIS__HOST: code-server-deet
      CODE_SERVERS__GSCIP__HOST: code-server-gscip
      CODE_SERVERS__LITE__HOST: code-server-lite
    volumes:
      - ${PWD}/teams:/app/teams
    links:
      - "db"
      - "redis"
      - "code-server-deet"
      - "code-server-gscip"
      - "code-server-data-science"
      - "code-server-lite"
      - "code-server-datasets-and-analysis"

  worker:
    build:
      context: .
      dockerfile: ./platform/Dockerfile
    command: dagster-celery worker start -A dagster_celery.app --config-yaml ./platform/executor.yaml
    environment:
      POSTGRES_URL: postgresql://postgres@db/postgres
      REDIS_URL: redis://redis/
      DAGSTER_HOME: /app/platform
    volumes:
      - ${PWD}/teams:/app/teams
    links:
      - "db"
      - "redis"

  code-server-deet: &code-server
    build:
      context: .
      dockerfile: ./platform/Dockerfile
    command: dagster code-server start --port 8080 --host 0.0.0.0 --module-name teams.deet
    healthcheck:
      test: ["CMD-SHELL", "echo '' > /dev/tcp/127.0.0.1/8080"]
      interval: 2s
      timeout: 2s
      retries: 5
      start_period: 2s
    environment:
      POSTGRES_URL: postgresql://postgres@db/postgres
      REDIS_URL: redis://redis/
      DAGSTER_HOME: /app/platform
    volumes:
      - ${PWD}/teams:/app/teams
    links:
      - "db"
      - "redis"

  code-server-data-science:
    <<: *code-server
    command: dagster code-server start --port 8080 --host 0.0.0.0 --module-name teams.data_science

  code-server-datasets-and-analysis:
    <<: *code-server
    command: dagster code-server start --port 8080 --host 0.0.0.0 --module-name teams.datasets_and_analysis

  code-server-gscip:
    <<: *code-server
    command: dagster code-server start --port 8080 --host 0.0.0.0 --module-name teams.gscip

  code-server-lite:
    <<: *code-server
    command: dagster code-server start --port 8080 --host 0.0.0.0 --module-name teams.lite

  redis:
    image: redis
