name: Tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version:
          - "3.11.0"
        postgresql-version:
          - "postgres:16beta2"
        # sqlalchemy 1.4 doesn't support psycopg3
        ci-extras:
          - ci-psycopg2-sqlalchemy1
          - ci-psycopg2-sqlalchemy2
          - ci-psycopg3-sqlalchemy2
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
      - uses: "actions/setup-python@v4"
        with:
          python-version: '${{ matrix.python-version }}'
      - name: "Run PostgreSQL"
        run: |
          cp sample.env .env
          docker compose up --build -d db
      - name: "Install requirements"
        run: |
          pip install -r requirements-dev.txt
      - name: "Wait for PostgreSQL"
        run: "timeout 60 bash -c 'until echo > /dev/tcp/127.0.0.1/5432; do sleep 5; done'"
      - name: "Test"
        run: |
          pytest --cov
      - uses: codecov/codecov-action@v3
